title: Annisa Siti Utami # your name (or website title) here
logo: "/images/Annisa Siti Utami.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduated Statistics student at Universitas Padjadjaran 
  <br><br>
  
  <a href="https://www.linkedin.com/in/annisa-siti-utami/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
